apiVersion: skaffold/v2beta18
kind: Config
metadata:
  name: dummy-agent

requires:
  - configs: ["cloud-spanner-emulator", "redis"]
    # path: ../dev-agents
    git:
      repo: git@github.com:CorrDyn/treatment-dev-agents.git
      ref: main
      path: ./skaffold.yaml

build:
  artifacts:
  - image: dummy-agent
    buildpacks:
      builder: "gcr.io/buildpacks/builder"
      trustBuilder: true
      env:
        - NODE_ENV=development
  local: {}

deploy:
  kubeContext: minikube
  kustomize:
    paths:
    - .k8s/local-dev

portForward:
- resourceType: Service
  resourceName: dummy-agent
  namespace: dummies
  port: 8080
