apiVersion: skaffold/v2beta18
kind: Config
metadata:
  name: dummy-agent

requires:
  - configs: ["cloud-spanner-emulator", "redis"]
    # path: ../dev-agents
    git:
      repo: git@github.com:CorrDyn/treatment-dev-agents.git
      ref: main
      path: ./skaffold.yaml

build:
  artifacts:
  - image: dummy-agent
    docker:
      # Use the image labeled as 'devel' in the Dockerfile
      target: devel
    sync:
      manual:
        - src: 'src/*'
          dest: '/opt/api'
  local: {}

deploy:
  kubeContext: minikube
  kustomize:
    paths:
    - .k8s/local-dev

portForward:
- resourceType: Service
  resourceName: dummy-agent
  namespace: dummies
  port: 8080
