apiVersion: skaffold/v2beta18
kind: Config
metadata:
  name: dummy-agent

requires:
  - configs: ["cloud-spanner-emulator", "redis"]
    # path: ../dev-agents
    git:
      repo: git@github.com:CorrDyn/treatment-dev-agents.git
      ref: main
      path: ./skaffold.yaml

build:
  artifacts:
  - image: dummy-agent
    docker:
      # Use the image labeled as 'devel' in the Dockerfile
      target: devel
    sync:
      manual:
        - src: 'src/*'
          dest: '/opt/api'
  local: {}

deploy:
  kubeContext: minikube
  kustomize:
    paths:
    - .k8s/local-dev

portForward:
- resourceType: Service
  resourceName: dummy-agent
  namespace: default
  port: 8080

profiles:
- name: development
  patches:
    # We don't need the local dev containers here
    - op: remove
      path: /requires
  build:
    googleCloudBuild: {}

  deploy:
    kubeContext: corrdyn-edge2mesh
    kustomize:
      paths:
      - .k8s/devel

- name: qa
  patches:
    # We don't need the local dev containers here
    - op: remove
      path: /requires
  build:
    artifacts:
    - image: dummy-agent
      docker:
        # Use the image labeled as 'prod' in the Dockerfile
        target: prod
        buildArgs:
          NODE_ENV: production
    googleCloudBuild: {}

  deploy:
    kubeContext: corrdyn-edge2mesh
    kustomize:
      paths:
      - .k8s/qa
