apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devel-dummies

resources:
  - ../bases
  - ./namespace.yaml

configMapGenerator:
- name: dummy-agent
  literals:
  - NODE_ENV=development
  - TRACING_ENABLED="true"
  - REDISURI="rediss://10.1.1.1/1"
  - SPANNER_INSTANCE=production-1
  - SPANNER_DB=devel-song-db
