kind: Service
apiVersion: v1
metadata:
  name: dummy-agent
spec:
  selector:
    app: dummy-agent

  ports:
  - name: http
    protocol: TCP
    port: 8080
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: dummy-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy-agent
  template:
    metadata:
      labels:
        app: dummy-agent
    spec:
      containers:
      - name: dummy-agent
        image: dummy-agent
        imagePullPolicy: "IfNotPresent"
        ports:
          - containerPort: 8080

        # Values defined in an env will always have precedence over
        # values defined in an envFrom. To override use valueFrom.
        env:
        - name: LISTEN_PORT
          value: "8080"

        envFrom:
        - configMapRef:
            name: dummy-agent
