name: Deploy to QA GKE
on:
  create:
    tags:
      - "v[0-9]+\.[0-9]+\.[0-9]+-qa"

env:
  PROJECT_ID: ${{ secrets.DEVEL_GCP_PROJECT }}
  # Should match skaffold profile deploy.kubeContext
  GKE_CLUSTER: corrdyn-edge2mesh
  GKE_ZONE: us-central1-c
  SKAFFOLD_DEFAULT_REPO: us.gcr.io/${{ secrets.DEVEL_GCP_PROJECT }}
  SKAFFOLD_PROFILE: qa

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository trunk
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Config GCP
        uses: google-github-actions/setup-gcloud@master
        with:
          version: '350.0.0'
          service_account_key: ${{ secrets.DEVEL_GCP_CREDS }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: "true"

      - name: Install K8s tools
        run: |-
          gcloud components install skaffold kustomize kubectl

      - name: GCP Auth
        run: |-
          gcloud --quiet auth configure-docker
          gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
          kubectl config rename-context $(kubectl config current-context) "$GKE_CLUSTER"

      - name: Deploy to GKE
        run: |-
          skaffold run --profile "$SKAFFOLD_PROFILE" --default-repo "$SKAFFOLD_DEFAULT_REPO"
